config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'

  devise_for :users, :controllers => {registrations: 'registrations'}
  mount Attachinary::Engine => "/attachinary"
  root to: "pages#home"

  resources :vans do
    resources :rentals, only: [:new, :create]
    resources :reviews, only: [:index, :new, :create]
  end

  resources :rentals, only: [:index, :show, :edit, :update, :destroy]
  resources :reviews, only: [:show, :edit, :update, :destroy]
  get 'users/:id/dashboard', to: 'users#dashboard', as: 'dashboard'
end

app/models/van.rb
class Van < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :rentals
  validates :location, :description, :photo, :make, :model, :bed, :sleep, :price, presence: true

  # Enables photo uploads
  mount_uploader :photo, PhotoUploader

  # Enables geocoder
  geocoded_by :location
  after_validation :geocode, if: :location_changed?

  include PgSearch
  pg_search_scope :global_search,
    against: [ :location ],
    associated_against: {
      rentals: [ :start_date, :end_date ]
    }
end

app/controllers/vans_controller.rb
class VansController < ApplicationController
  before_action :set_van, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @vans = policy_scope(Van).where.not(latitude: nil, longitude: nil).order(created_at: :desc)

    @coordinates = @vans.map do |van|
      if van.latitude && van.longitude
        {
          lat: van.latitude,
          lng: van.longitude,
          infowindow: render_to_string(partial: "vans/infowindow", locals: {van: van}),
        }
      end
    end
    @results = params[:query].present? ? Van.global_search(params[:query]) : Van.all
  end

  def show
    authorize @van
    @rental = Rental.new



    @hash = Gmaps4rails.build_markers(@van) do |van, marker|
      marker.lat van.latitude
      marker.lng van.longitude
    end
  end

  def new
    @van = Van.new
    authorize @van
  end

  def create
    @van = Van.new(van_params)
    @van.user = current_user
    authorize @van

    if @van.save
      redirect_to van_path(@van)
    else
      render :new
    end
  end

  def edit
    authorize @van
  end

  def update
    authorize @van
    if @van.update(van_params)
      redirect_to van_path(@van)
    else
      render :edit
    end
  end

  def destroy
    authorize @van
    @van.destroy
    redirect_to vans_path
  end

  private

  def van_params
    params.require(:van).permit(:location, :availability, :description, :make, :model, :bed, :sleep, :bathroom, :kitchen, :price, :photo)
  end

  def set_van
    @van = Van.find(params[:id])
  end
end

app/views/vans/_form.html.erb
<%= simple_form_for(@van) do |v| %>
  <%= v.input :location %>
  <%= v.input :description %>
  <%= v.input :price %>
  <%= v.input :make %>
  <%= v.input :model %>
  <%= v.input :bed %>
  <%= v.input :sleep %>
  <%= v.input :bathroom %>
  <%= v.input :kitchen %>
  <%= v.input :photo %>
  <%= v.input :photo_cache, as: :hidden %>
  <%= v.submit "Submit", class: "btn btn-default" %>
<% end %>

app/views/vans/_infowindow.html.erb
<div class="window">
  <div id="description">
    <h1><%= van.make.upcase %> <%= van.model.upcase %></h1>
    <h2>Listed by <strong><%= User.find(van.user_id).first_name %></strong></h2>
    <h2>Price: £<%= number_with_delimiter(van.price) %></h2>
    <br>
    <p><%= van.description %></p>
  </div>

  <div id="photo">
    <%= cl_image_tag van.photo, width: 100, height: 150, crop: :fill %>
  </div>
</div>

app/views/vans/edit.html.erb
<div class="container">

<h2>Edit <%= @van.make.capitalize %> <%= @van.model.capitalize %></h2>

  <h2>Edit New Van</h2>

  <%= render "form", van: @van %>

  <hr>

  <%= link_to vans_path do %>
    <i class="fa fa-undo" aria-hidden="true"></i> Back to List
  <% end %>

  <%= content_for(:title, 'Edit your van - Le Campeur') %>

</div>

app/views/vans/index.html.erb
<!-- Geocoding Map -->
<div id="map" class="hidden-map" style="width: 100%;"></div>

<!-- Results Display -->
<div class="cards">

  <% @results.each do |van| %>
    <% photo_url = van.photo? ? van.photo : 'lix2bqmp4kzdpu4sqjiy' %>
    <div class="card" style="background-image: linear-gradient(rgba(255,255,255,0.2),rgba(0,0,0,0.2)), url(<%= cl_image_path photo_url %>);">
      <div class="card-body">
        <h4><%= van.make.upcase %></h4>
        <p><%= van.location.upcase %> | £<%= number_with_delimiter(van.price) %></p>
        <%= link_to "", van_path(van), class: "card-link" %>
      </div>
    </div>
  <% end %>
</div>

<!-- Button: Show Map -->
<div id="arrow">
  <h4><button id="display-button" class="btn btn-default" type="geocode"><i class="fa fa-location-arrow" aria-hidden="true"></i></button></h4>
</div>

<%= content_for(:title, 'Le Campeur') %>

<% content_for(:after_js) do %>
  <script>
    // Snazzy Maps - Theme: Cool Grey
    var styles = [
                  {
                      "featureType": "landscape",
                      "elementType": "labels",
                      "stylers": [
                          {
                              "visibility": "off"
                          }
                      ]
                  },
                  {
                      "featureType": "transit",
                      "elementType": "labels",
                      "stylers": [
                          {
                              "visibility": "off"
                          }
                      ]
                  },
                  {
                      "featureType": "poi",
                      "elementType": "labels",
                      "stylers": [
                          {
                              "visibility": "off"
                          }
                      ]
                  },
                  {
                      "featureType": "water",
                      "elementType": "labels",
                      "stylers": [
                          {
                              "visibility": "off"
                          }
                      ]
                  },
                  {
                      "featureType": "road",
                      "elementType": "labels.icon",
                      "stylers": [
                          {
                              "visibility": "off"
                          }
                      ]
                  },
                  {
                      "stylers": [
                          {
                              "hue": "#00aaff"
                          },
                          {
                              "saturation": -100
                          },
                          {
                              "gamma": 2.15
                          },
                          {
                              "lightness": 12
                          }
                      ]
                  },
                  {
                      "featureType": "road",
                      "elementType": "labels.text.fill",
                      "stylers": [
                          {
                              "visibility": "on"
                          },
                          {
                              "lightness": 24
                          }
                      ]
                  },
                  {
                      "featureType": "road",
                      "elementType": "geometry",
                      "stylers": [
                          {
                              "lightness": 57
                          }
                      ]
                  }
                ];
    // Toggle Button for Map Display
    const map = document.getElementById("map");
    document.getElementById('display-button').onclick = function() {
      map.classList.toggle("shown-map");
    };

    // Geocoding
    var handler = Gmaps.build("Google");
    handler.buildMap({
      provider: {
        styles: styles
      }, internal: { id: "map" } }, function() {
      markers = handler.addMarkers(<%= raw @coordinates.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      handler.getMap().setZoom(14);
    });
  </script>
<% end %>

app/views/vans/new.html.erb
<div id="new_background">
  <div class="container">
    <h2>Add a new van</h2>

    <%= render "form", van: @van %>

  <hr>

  <%= link_to vans_path do %>
    <i class="fa fa-undo" aria-hidden="true"></i> Back to List
  <% end %>

  <%= content_for(:title, 'Add new van - Le Campeur') %>
  </div>
</div>

app/views/vans/show.html.erb
<div class="display">
  <!-- Banner -->
  <% photo_url = @van.photo? ? @van.photo : 'lix2bqmp4kzdpu4sqjiy' %>
  <div class="image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path photo_url %>)">
    <!-- Title and Booking -->
    <div class="booking">
      <h1><%= @van.make.upcase %> <%= @van.model.upcase %></h1>
      <h4><%= @van.description %></h4>
      <h6>£<%= number_with_delimiter(@van.price) %></h6><br>
      <!-- Book Van -->
      <h3>
        <% if policy(@van).edit? == false %>
          <%= link_to "BOOK", new_van_rental_path(@van),class: "btn btn-default" %>
        <% end %>
        <!-- Edit Van -->
        <% if policy(@van).edit? %>
          <%= link_to "EDIT", edit_van_path(@van), class: "btn btn-default" %>
        <% end %>
        <!-- Delete Van -->
        <% if policy(@van).destroy? %>
          <%= link_to "DELETE", van_path(@van), class: "btn btn-default", method: :delete, data: { confirm: "Are you sure you want to delete?" } %>
        <% end %>
      </h3>
    </div>
  </div>

  <!-- Map Display -->
  <div class="location">
      <div id="map-show" style="width: 100%; height: 100%;"></div>
  </div>

  <!-- Details -->
  <div class="details">
    <div class="spacing">
      <!-- Geocoding on location? -->
      <h5><strong>LOCATION</strong></h5>
      <p><%= @van.location %></p>
      <br>
      <h5><strong>DETAILS</strong></h5>
      <ul-inline>
        <li>
          <i class="fa fa-bed" aria-hidden="true"></i>&nbsp
          <%= pluralize @van.bed, "bed" %> |
          <%= pluralize @van.sleep, "person" %>
        </li>
        <li>
          <i class="fa fa-bath" aria-hidden="true"></i>&nbsp
          <%= @van.bathroom ? "Bathroom included" : "Bathroom not included" %>
        </li>
        <li>
          <i class="fa fa-fire" aria-hidden="true"></i>&nbsp
          <%= @van.kitchen ? "Kitchen included" : "Kitchen not included" %></li>
      </ul>
    </div>
  </div>

  <!-- Reviews -->
  <div class="reviews">
    <div class="spacing">
      <h5>
        <strong>REVIEWS</strong>&nbsp
        (<%= pluralize @van.reviews.count, "review" %>)
      </h5>
      <p>
        <div class="link">
          <!-- Add Reviews -->
          <% if policy(@van).edit? == false %>
            <%= link_to "ADD", new_van_review_path(@van) %> &nbsp|&nbsp
          <% end %>
          <!-- List All Reviews for Van -->
          <%= link_to "SHOW ALL", van_reviews_path(@van) %>
        </div>
      </p>
      <!-- Pop Up -->
      <ul-inline>
        <% @van.reviews.last(5).each do |review| %>
          <li>
            <% review.score.times do %>
              <i class="fa fa-star"></i>
            <% end %>
            <% (5 - review.score).times do %>
              <i class="fa fa-star-o"></i>
            <% end %>
            - <%= User.find(review.user_id).first_name %> | <%= review.created_at.strftime("%d %b %Y") %> &nbsp
            <!-- Pop Up "Link" -->
            <div class="popup" id="popupclick" onclick >
              <div class="icon"><i class="fa fa-search" aria-hidden="true"></i></div>
              <!-- Pop Up Display -->
              <span class="popuptext" id="popup-display">
                <p>
                  <% review.score.times do %>
                    <i class="fa fa-star"></i>
                  <% end %>
                  <% (5 - review.score).times do %>
                    <i class="fa fa-star-o"></i>
                  <% end %>
                </p>
                <p><%= review.description %></p>
                <p>
                  <% if review.photo? %>
                    <%= cl_image_tag review.photo, height: 130, width: 130, crop: :fill %>
                  <% end %>
                    </p>
              </span>
              </div>
          </li>
        <% end %>
      </ul-inline>
    </div>
  </div>
</div>

<% content_for(:after_js) do %>
  <script>
    // Google Maps
    var handler = Gmaps.build('Google');
    handler.buildMap({ internal: { id: 'map-show' } }, function() {
      markers = handler.addMarkers(<%= raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      handler.getMap().setZoom(14);
    });
    // Snazzy Maps - Theme: Cool Grey
    var styles = [
                  {
                      "featureType": "landscape",
                      "elementType": "labels",
                      "stylers": [
                          {
                              "visibility": "off"
                          }
                      ]
                  },
                  {
                      "featureType": "transit",
                      "elementType": "labels",
                      "stylers": [
                          {
                              "visibility": "off"
                          }
                      ]
                  },
                  {
                      "featureType": "poi",
                      "elementType": "labels",
                      "stylers": [
                          {
                              "visibility": "off"
                          }
                      ]
                  },
                  {
                      "featureType": "water",
                      "elementType": "labels",
                      "stylers": [
                          {
                              "visibility": "off"
                          }
                      ]
                  },
                  {
                      "featureType": "road",
                      "elementType": "labels.icon",
                      "stylers": [
                          {
                              "visibility": "off"
                          }
                      ]
                  },
                  {
                      "stylers": [
                          {
                              "hue": "#00aaff"
                          },
                          {
                              "saturation": -100
                          },
                          {
                              "gamma": 2.15
                          },
                          {
                              "lightness": 12
                          }
                      ]
                  },
                  {
                      "featureType": "road",
                      "elementType": "labels.text.fill",
                      "stylers": [
                          {
                              "visibility": "on"
                          },
                          {
                              "lightness": 24
                          }
                      ]
                  },
                  {
                      "featureType": "road",
                      "elementType": "geometry",
                      "stylers": [
                          {
                              "lightness": 57
                          }
                      ]
                  }
                ];
      handler.buildMap({
        provider: {
          styles: styles
        }, internal: { id: "map-show" } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        handler.getMap().setZoom(14);
      });
    // Pop Up

    // popup.classList.toggle("show");

        var popup = document.querySelectorAll("#popupclick");
        popup.forEach(function(value) {
          id = 1;
          value.classList.add(`popup${id}`);
          id = id + 1;
          });
        popup.forEach(function(element) {
          element.addEventListener("click", (event) => {
            element.children[1].classList.toggle("show")
          })
        });
  </script>
<% end %>

<%= content_for(:title, 'Rent a '+ @van.model) %>