config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'

  devise_for :users, :controllers => {registrations: 'registrations'}
  mount Attachinary::Engine => "/attachinary"
  root to: "pages#home"

  resources :vans do
    resources :rentals, only: [:new, :create]
    resources :reviews, only: [:index, :new, :create]
  end

  resources :rentals, only: [:index, :show, :edit, :update, :destroy]
  resources :reviews, only: [:show, :edit, :update, :destroy]
  get 'users/:id/dashboard', to: 'users#dashboard', as: 'dashboard'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/lewagon"><i class="fa fa-github"></i></a>
    <a href="https://www.instagram.com/lewagonlondon/"><i class="fa fa-instagram"></i></a>
    <a href="https://www.facebook.com/lewagonlondon/"><i class="fa fa-facebook"></i></a>
    <a href="https://twitter.com/lewagonlondon?lang=en"><i class="fa fa-twitter"></i></a>
    <a href="https://www.linkedin.com/school/5046700/"><i class="fa fa-linkedin"></i></a>
  </div>

  <div class="footer-copyright">
    &copy; Le Campeur - Rent a Van with Us
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to vans_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Search bar -->
  <div class="search">
    <%= form_tag(vans_path, method: :get) do |f| %>
      <%= text_field_tag :query, nil, placeholder: 'Type your address', class: 'first_box' %>
      <%= date_field :rental, :start_date, value: Date.today, class: 'second_box' %>
      <%= date_field :rental, :end_date, value: Date.tomorrow, class: 'third_box' %>
      <button class="btn btn-default" style="border-radius: 50%; font-size: 12px; padding: 5px 10px !important" %>
        <i class="fa fa-search" aria-hidden="true"></i>
      </button>
    <% end %>
  </div>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

    <!-- Links when logged in -->
      <!-- Add New Van -->
      <%= link_to "ADD NEW VAN", new_van_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", data: { toggle: 'dropdown'} %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to dashboard_path(current_user), method: :get do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
             <li>
              <%= link_to rentals_path, method: :get do %>
                <i class="fa fa-tachometer"></i> <%= t(".dashboard", default: "Dashboard") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Profile</a></li>
        <li><a href="#">Dashboard</a></li>
        <li><a href="#">Log Out</a></li>
      </ul>
    </div>
  </div>
</div>