config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'

  devise_for :users, :controllers => {registrations: 'registrations'}
  mount Attachinary::Engine => "/attachinary"
  root to: "pages#home"

  resources :vans do
    resources :rentals, only: [:new, :create]
    resources :reviews, only: [:index, :new, :create]
  end

  resources :rentals, only: [:index, :show, :edit, :update, :destroy]
  resources :reviews, only: [:show, :edit, :update, :destroy]
  get 'users/:id/dashboard', to: 'users#dashboard', as: 'dashboard'
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :user
  belongs_to :van
  validates :start_date, :end_date, presence: true
  # validates :start_date, :end_date, :price, :status, :photo, presence: true

  mount_uploader :photo, PhotoUploader
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
    before_action :set_rental, only: [:show, :edit, :update, :destroy]
    before_action :set_van, only: [:new, :create]
    before_action :set_user, only: [:index]
    helper_method :weather_forecast

  def index
    @rentals = policy_scope(Rental)
    @my_rentals = @user.rentals
    @user_name = @user.first_name

    # @counter = "col-xs-4"
    # if @rentals.count == 1
    #   @counter = "col-xs-12"
    # elsif @rentals.count == 2
    #   @counter = "col-xs-6"
    # else
    #   @counter = "col-xs-4"
    # end


    @next_trip = @my_rentals.order(start_date: :desc).first

    if @next_trip
      @next_van = @next_trip.van
      @latitude = @next_van.longitude
      @latitude = @next_van.latitude
      @next_trip_start = @next_trip.start_date
      @days_to_go = (@next_trip_start - Date.today + 1).to_i
      @next_location = @next_van.location
      weather_forecast
    end

    # Setting message based on trip count
    if @my_rentals.count.zero?
      @status = "No trips booked yet - why not book one?"
    elsif @my_rentals.count == 1
      @status = "You have #{@rentals.count} trip booked!"
      @status_two = "You are off to #{@next_location}"
      @days_to_go == 1 ? @status_three = "Only #{@days_to_go} day to go!" : @status_three = "Only #{@days_to_go} days to go!"
      @status_four = "The current weather there is #{@weather}."
    else
      @status = "You have #{@rentals.count} trips booked!"
      @status_two = "You are off to #{@next_location} next!"
      @days_to_go == 1 ? @status_three = "Only #{@days_to_go} day to go!" : @status_three = "Only #{@days_to_go} days to go!"
      @status_four = "The current weather there is #{@weather}."
    end

    owned_vans = @user.vans
    no_of_rentals = Rental.where(van: owned_vans).count

    # Setting status for van owners
    @user_owns_a_van = !@user.vans.empty?
    if @user_owns_a_van && no_of_rentals > 0
      no_of_rentals == 1 ? @rented_message_one = "You have one #{no_of_rentals} rental" : "Sweet you have one #{no_of_rentals} rentals"
      no_of_rentals == 1 ? @rented_message_two = "Superb - with the money from those you can have some beers!" : "Wow - with those rentals you will be a millionaire!"
    elsif @user_owns_a_van == true
      @rented_message_one = "No rentals just yet why edit your van description to make it even better!"
      @rented_message_two = "Or on second thoughts take it on a road trip!"
    end
  end

  def new
    @rental = Rental.new
    authorize @rental
  end

  def create
    @rental = Rental.new(rental_params)
    @rental.van = @van
    @rental.user = current_user
    authorize @rental
    if @rental.save
      redirect_to rentals_path
    else
      render :new
    end
  end

  def show
    authorize @rental
    @van = Van.find(@rental.van_id)
    @renter = User.find(@rental.user_id)
    @owner = User.find(@van.user_id)
  end

  def edit
    authorize @rental
  end

  def update
    authorize @rental
    if @rental.update(rental_path)
      redirect_to rental_path(@rental)
    else
      render :edit
    end
  end

  def destroy
    authorize @rental
    @rental.destroy
    redirect_to root_path
  end

  private

  def rental_params
    params.require(:rental).permit(:start_date, :end_date, :photo, :price, :status)
  end

  def set_van
    @van = Van.find(params[:van_id])
  end

  def set_rental
    @rental = Rental.find(params[:id])
  end

  def set_user
    @user = current_user
  end

  def weather_forecast
    require 'json'
    require 'open-uri'
    key = ENV['OPEN_WEATHER_KEY']
    latitude = 20
    longitude = 20
    url = "http://api.openweathermap.org/data/2.5/forecast?lat=#{latitude}&lon=#{longitude}&APPID=#{key}"
    weather_serialized = open(url).read
    @forecast = JSON.parse(weather_serialized)
    @weather = ["#{@forecast["list"][7]["weather"][0]["main"]}"].join.downcase
  end
end

app/views/rentals/index.html.erb
<div class="show-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)), url('http://res.cloudinary.com/joycelewagon/image/upload/v1510750617/hfxsxwnvfij3w15mvccl.jpg')">
  <div class="booking">
    <h1><%= @status %> Time to get excited <%= @user_name %></h1>
    <h2><%= @rented_message_one %> <%= @rented_message_two %></h2>
    <h2><%= @status_two %> <%= @status_three %> <%= @status_four %></h2>
  </div>
</div>

<div class="container margin-top">
  <div class="row">
    <% @rentals.each do |rental| %>
    <div class="col-xs-4">
      <% @van = rental.van %>
      <% @van_owner = @van.user %>
      <% @rating = Review.where(van: @van).average(:score).to_i %>
      <% days = (rental.start_date - Date.today).to_i %>

      <div class="booking__card text-center">
        <div class="card__thumb" style="background-image: url('<%= cl_image_path rental.van.photo, width: 800, height: 400, crop: :fill %>')">
        </div>
        <div class="card__date">
          <span class="card__date__day"><%= rental.start_date.strftime("%d") %></span>
          <br/>
          <span class="card__date__month"><%= rental.start_date.strftime("%b") %></span>
        </div>


        <div class="card__body">
          <div class="card__category"><%= days %> days until you are off to <%= rental.van.location %></div>
          <h2 class="card__title"></h2>
          <div class="card__subtitle"><%= rental.van.make %></div>
          <div class="card__description">
            <h5><strong>DETAILS</strong></h5>
            <ul>
              <li>
                <i class="fa fa-bed" aria-hidden="true"></i>&nbsp
                <%= @van.bed %> bed(s) | <%= @van.sleep %> person(s)
              </li>
              <li>
                <i class="fa fa-bath" aria-hidden="true"></i>&nbsp
                <%= @van.bathroom ? "Bathroom included" : "Bathroom not included" %>
              </li>
              <li>
                <i class="fa fa-fire" aria-hidden="true"></i>&nbsp
                <%= @van.kitchen ? "Kitchen included" : "Kitchen not included" %>
              </li>
            </ul>
          </div>
        </div>
        <div class="card__footer">
          <span class="icon ion-clock"></span>
          <% if @rating != 0 %>
          Average rating <%= @rating %>
          <% else %>
          Not yet rated!
          <% end %>
          <span class="icon ion-chatbox"></span><a href="#"></a>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/rentals/new.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('http://res.cloudinary.com/joycelewagon/image/upload/v1510758702/n5i4cunpvbegw2e5nrxw.jpg');">
  <div class="booking-container">
    <div class="banner-content">
        <div class="container-banner">
          <h1>Book this van!</h1>
        </div>
    </div>
    <div class="form-container">
      <%= simple_form_for [@van, @rental] do |r| %>
      <div class="form-label-container">
        <%= r.label "When do you want to pick up your camper?" %>
      </div>
        <%= r.input :start_date, label: false %>
      <div class="form-label-container">
        <%= r.label "When does your journey end?" %>
       </div>
      <%= r.input :end_date, label: false %>
      <%= r.submit "Submit", class: "btn btn-default" %>
      <% end %>
    </div>
    <%= link_to van_path(@van) do %>
      <i class="fa fa-undo" aria-hidden="true"></i> Return to this van
    <% end %>
    <%= content_for(:title, 'New rental - Le Campeur') %>
  </div>
</div>

app/views/rentals/show.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('http://res.cloudinary.com/joycelewagon/image/upload/v1510750617/hfxsxwnvfij3w15mvccl.jpg');">
  <div class="banner-content">
    <h1>Confirmed</h1>
  </div>
</div>

<h1>Here are the details of your rental</h1>

<p><%= @renter.first_name %> you are renting from <%= @owner.first_name %></p>

<p>Rental start date: <%= @rental.start_date.strftime("%m/%d/%Y") %>
<p>Rental end date: <%= @rental.end_date.strftime("%m/%d/%Y") %>
<p>Your rental is: <%= @rental.status %>
<p>Total price of the rental: <%= @rental.price %>

<h2>The details of <%= @owner.first_name %>'s van</h2>

<p>It has <%= @van.bed %>beds</p>

<% if policy(@rental).edit? %>
  <%= link_to "Edit Rental", edit_rental_path(@rental) %>
<% end %>

<% if policy(@rental).destroy? %>
  <%= link_to "Delete Rental", rental_path(@rental), method: :delete, data: { confirm: "Are you sure you want to delete?" } %>
<% end %>

<%= content_for(:title, 'Le Campeur') %>